export const Icons = {
  // ── 导航 ──
  home: 'material-symbols:home-rounded',
  library: 'material-symbols:library-music',
  settings: 'material-symbols:settings-rounded',
  explore: 'material-symbols:explore-rounded',
  radio: 'material-symbols:radio-rounded',
  podcast: 'material-symbols:podcasts-rounded',

  // ── 播放控制 ──
  play: 'material-symbols:play-arrow-rounded',
  pause: 'material-symbols:pause-rounded',
  skipNext: 'material-symbols:skip-next-rounded',
  skipPrev: 'material-symbols:skip-previous-rounded',
  fastForward: 'material-symbols:fast-forward-rounded',
  rewind: 'material-symbols:fast-rewind-rounded',
  shuffle: 'material-symbols:shuffle-rounded',
  repeat: 'material-symbols:repeat-rounded',
  repeatOne: 'material-symbols:repeat-one-rounded',
  queue: 'material-symbols:queue-music-rounded',
  list: 'material-symbols:format-list-bulleted-rounded',
  stop: 'material-symbols:stop-rounded',
  eject: 'material-symbols:eject-rounded',

  // ── 操作 ──
  search: 'material-symbols:search-rounded',
  chevronDown: 'material-symbols:keyboard-arrow-down-rounded',
  chevronUp: 'material-symbols:keyboard-arrow-up-rounded',
  chevronLeft: 'material-symbols:chevron-left-rounded',
  chevronRight: 'material-symbols:chevron-right-rounded',
  more: 'material-symbols:more-vert',
  moreHoriz: 'material-symbols:more-horiz-rounded',
  close: 'material-symbols:close-rounded',
  check: 'material-symbols:check-rounded',
  add: 'material-symbols:add-rounded',
  remove: 'material-symbols:remove-rounded',
  edit: 'material-symbols:edit-rounded',
  delete: 'material-symbols:delete-rounded',
  menu: 'material-symbols:menu-rounded',
  menuOpen: 'material-symbols:menu-open-rounded',
  refresh: 'material-symbols:refresh-rounded',
  undo: 'material-symbols:undo-rounded',
  redo: 'material-symbols:redo-rounded',
  dragHandle: 'material-symbols:drag-handle-rounded',
  filter: 'material-symbols:filter-alt-rounded',
  sort: 'material-symbols:sort-rounded',

  // ── 内容 ──
  heart: 'material-symbols:favorite-rounded',
  heartOutline: 'material-symbols:favorite-outline-rounded',
  bookmark: 'material-symbols:bookmark-rounded',
  bookmarkOutline: 'material-symbols:bookmark-outline-rounded',
  share: 'material-symbols:share-rounded',
  history: 'material-symbols:history-rounded',
  clock: 'material-symbols:schedule-rounded',
  calendar: 'material-symbols:calendar-month-rounded',
  download: 'material-symbols:download-rounded',
  downloadDone: 'material-symbols:download-done-rounded',
  upload: 'material-symbols:upload-rounded',
  pin: 'material-symbols:push-pin',
  cloud: 'material-symbols:cloud',
  cloudOff: 'material-symbols:cloud-off',
  musicNote: 'material-symbols:music-note-rounded',
  album: 'material-symbols:album',
  mic: 'material-symbols:mic-rounded',
  lyrics: 'material-symbols:lyrics-rounded',
  equalizer: 'material-symbols:equalizer-rounded',
  graphicEq: 'material-symbols:graphic-eq-rounded',
  volumeUp: 'material-symbols:volume-up-rounded',
  volumeDown: 'material-symbols:volume-down-rounded',
  volumeMute: 'material-symbols:volume-mute-rounded',
  volumeOff: 'material-symbols:volume-off-rounded',
  playlistAdd: 'material-symbols:playlist-add-rounded',
  playlistPlay: 'material-symbols:playlist-play-rounded',
  trendingUp: 'material-symbols:trending-up-rounded',
  trendingDown: 'material-symbols:trending-down-rounded',
  fire: 'material-symbols:local-fire-department-rounded',
  star: 'material-symbols:star-rounded',

  // ── 设置 ──
  palette: 'material-symbols:palette',
  info: 'material-symbols:info-rounded',
  help: 'material-symbols:help-rounded',
  person: 'material-symbols:person-rounded',
  logout: 'material-symbols:logout-rounded',
  darkMode: 'material-symbols:dark-mode-rounded',
  lightMode: 'material-symbols:light-mode-rounded',
  notifications: 'material-symbols:notifications-rounded',
  language: 'material-symbols:language-rounded',
  storage: 'material-symbols:storage-rounded',
  security: 'material-symbols:security-rounded',
  tune: 'material-symbols:tune-rounded',
} as const
